### ISSUE TITLE
is this stable yet?

### ISSUE THREAD

**Issue by jtkeyva** [thruthesky/all_in_one#59]
thanks for this, looks like your next iteration of fireflutter & firelamp? i want to try it out but hard to translate, and want to make sure this is under active development.
cheers

**Comment by thruthesky** [comment]
@jtkeyva Sorry for late response. I should find a way how to get notified when there is an issue or reply on github.

This all_in_one project is some what different project from fireflutter. It is more like a sample(scaffolding) project for flutter learners.
